name: mlLearningEnv

channels:
  - conda-forge

dependencies:
  # The basics
  - python=3.12
  - numpy=1.26
  - matplotlib=3.9
  - scipy
  - pip

  # Physics
  - vector

  # Machine learning
  - scikit-learn

  - pip:
    - --index-url https://download.pytorch.org/whl/cu126
    - torch==2.6.0
    - torchvision==0.21.0